#lang sicp
(load "F:\\workspace\\sicp\\sicp.scm")

(define (cons a b)
  (* (fast-expt 2 a)
     (fast-expt 3 b)))
(define (car c)
  (if (divides? 3 c)
      (car (/ c 3))
      (/ (log c) (log 2))
      ))
(define (cdr c)
  (if (divides? 2 c)
      (cdr (/ c 2))
      (/ (log c) (log 3))))
;; 莫名其妙要多运行几次才行，不然car和cdr方法没覆盖
(display (cons 2 4))
(newline)
(display (car (cons 2 4)))
(newline)
(display (cdr (cons 2 4)))
